### ISSUE TITLE
Extract gives just the first part of the highlighted part

### ISSUE THREAD

**Issue by The-Minh** [gunawanlie/atom-regex-extractor#12]
# Context
I'm using your (awesome) plugin to try to extract more than 200 occurrences of the following method calls:
`Slack::company.channel("message content")`
Especially, I want to extract the channel and message content. But the extract does not contain the expected extracts.

# Steps to reproduce the problem
1. My files contain something like
`Slack::company.channel("message content")`
2. My regex `(?<=Slack::company.).*?(?=\))` gives the expected results
3. When I extract (I tried the 3 options), I get a file containing as many occurrences of `Slack::company` as there are in the results.

**Comment by gunawanlie** [comment]
> 3\. When I extract (I tried the 3 options), I get a file containing as many occurrences of `Slack::company` as there are in the results.

Hi @The-Minh , can you elaborate this part (3rd step) ?

Following your step 1 and 2, your current regex
**`(?<=Slack::company.).*?(?=\))`**
could extract
**`channel("message content"`**
from the text
**`Slack::company.channel("message content")`**
as in your example.  Is this not what you expect ?

Can you give me clearer expected result from your sample text `Slack::company.channel("message content")` ?

do you want the result to be like `channel("message content")` ? or ... ?

**Comment by The-Minh** [comment]
Hey thanks for the quick answer! Here it is in action (should have done that with the 1st message): 
https://www.loom.com/share/dff4d6f8ab404cb489ef2edd96484a73

**Comment by gunawanlie** [comment]
Hi @The-Minh , what I can see from your video, there are 2 missing steps:
- make sure when you search, you **TOGGLE ON** the regex option, at least in your video, it was off.
- the regex pattern you mentioned before, wasn't set in the "Find Field", in your video.

sample:
![Screenshot 2020-08-28 at 12 08 00 AM](https://user-images.githubusercontent.com/2569388/91466985-7efc8800-e8c2-11ea-8ae4-c3ff13a849f1.png)

hope this help on your task

**Comment by The-Minh** [comment]
Works perfectly now… Not sure what I missed before, but problem solved. Well thank you a lot!
